/**
 * Admin Panel and cheat commands.
 *
 * Authorisation: every request is checked here, on the server, against the
 * sender's role (world owner or operator) and the world's cheats setting.
 *
 * Advancement safety: everything a cheat creates is marked (items get an
 * `admin` tag, mobs and other entities an `admin` flag, placed blocks a
 * position mark, XP an admin share), cheat teleports mark the place (or the
 * whole visit to another dimension) the player arrived in, and cheat game
 * modes and flight mark the player while they last. Advancements are only
 * granted outside that context (see Interaction.grant), and the marks carry
 * through crafting, smelting, brewing, trading, breeding and drops, so a chain
 * of events started by a cheat stays advancement-neutral. Normal play is
 * untouched.
 */
import type { GameServer } from '../GameServer';
import type { ServerPlayer } from '../player/ServerPlayer';
import type { Dimension } from '../world/Dimension';
import type { Entity } from '../entity/Entity';
import { Mob } from '../entity/Mob';
import { validateAdmin, xpForLevel, structureName, ADMIN_DIMENSIONS, type AdminAction, type AdminCatalog, type LocateResult, type V4Op } from '../../common/game/admin';
import { GlitchedQuestSystem } from '../systems/GlitchedQuest';
import { StructureQuests } from '../systems/StructureQuests';
import type { Start } from '../../common/gen/structures/manager';
import { itemById, items, itemOf } from '../../common/registry/items';
import { markAdmin, isAdminStack, stackOf, type ItemStack, type Slot } from '../../common/game/itemstack';
import { POTION_BY_ID } from '../../common/data/potions';
import { ENCHANT_BY_ID } from '../../common/data/enchantments';
import { MOB_DEFS, mobDef } from '../../common/data/mobs';
import { biomes, biomeOf } from '../../common/registry/biomes';
import { maxHealthFor } from '../../common/game/gamemode';
import { STATE_SOLID, STATE_FLUID, STATE_BLOCK, blocks, S, stateOf, withProp, hasProp } from '../../common/registry/blocks';
import { rollLoot } from '../../common/game/loot';
import { Random } from '../../common/math/rng';
import { chunkIndex } from '../../common/world/constants';
import type { DimensionId } from '../../common/data/biomes';
import { ADMIN_ZONE_RADIUS, MAX_ADMIN_ZONES } from './adminState';
import { CAVE_BIOMES } from '../../common/gen/caves/caveBiomes';

/** Work budget for searches per server tick (ms). */
const SEARCH_BUDGET_MS = 6;
/** Farthest a biome search looks (blocks). */
const BIOME_RADIUS = 6144;
const HAZARD = /lava|magma|fire|cactus|campfire|sweet_berry|powder_snow|wither_rose|portal|pointed_dripstone/;

interface Search {
  p: ServerPlayer;
  req: number;
  kind: 'structure' | 'biome' | 'cave';
  dim: DimensionId;
  id: string;
  teleport: boolean;
  steps: Generator<void, { x: number; y: number; z: number } | null>;
  started: number;
}

interface PendingTp {
  p: ServerPlayer;
  req: number;
  dim: DimensionId;
  x: number;
  y: number;
  z: number;
  label: string;
  surface: boolean;
  since: number;
}

interface LevelAdmin {
  sky?: boolean;
  blocks?: Record<string, Record<string, number[]>>;
  chunks?: Record<string, number[]>;
}

export class AdminService {
  /** > 0 while an admin action runs: everything it causes is cheat-made. */
  private depth = 0;
  private readonly searches: Search[] = [];
  private readonly pending: PendingTp[] = [];
  private readonly budget = new Map<ServerPlayer, number>();
  /** Positions of blocks placed or formed by cheats: dim -> chunk key -> packed local index. */
  private readonly blockMarks = new Map<string, Map<number, Set<number>>>();
  /** Chunks regenerated by cheats (everything in them counts as cheat-made). */
  private readonly chunkMarks = new Map<string, Set<number>>();
  private lastDayTime = -1;

  constructor(private readonly server: GameServer) {
    this.load();
  }

  // ------------------------------------------------------------------ authorisation

  /** Owner or operator of a world with cheats enabled. */
  allowed(p: ServerPlayer): boolean {
    return this.server.level.cheats && this.server.isOperator(p);
  }

  /** Runs a function as an admin action (its side effects are cheat-made). */
  run<T>(fn: () => T): T {
    this.depth++;
    try {
      return fn();
    } finally {
      this.depth--;
    }
  }

  get active(): boolean {
    return this.depth > 0;
  }

  // ------------------------------------------------------------------ cheat context

  /** Whether a player's current actions are covered by a cheat (no advancements, items marked). */
  inContext(p: ServerPlayer): boolean {
    if (this.depth > 0) return true;
    const c = p.cheat;
    if (c.mode || c.flight) return true;
    if (c.visit && p.dim && c.visit === p.dim.id) return true;
    if (!p.dim) return false;
    const r2 = ADMIN_ZONE_RADIUS * ADMIN_ZONE_RADIUS;
    for (const z of c.zones) if (z.dim === p.dim.id && (p.x - z.x) ** 2 + (p.z - z.z) ** 2 < r2) return true;
    return false;
  }

  /** Marks a stack when the player is in a cheat context; returns it. */
  mark<T extends ItemStack>(p: ServerPlayer | null, s: T, extra = false): T {
    if (extra || (p && this.inContext(p))) markAdmin(s);
    return s;
  }

  isAdminStack(s: Slot | undefined): boolean {
    return isAdminStack(s);
  }

  /** Whether the time of day or weather was last set by a cheat (sleeping doesn't count then). */
  get skyTainted(): boolean {
    return !!this.levelAdmin().sky;
  }

  /** A cheat set the time of day or weather (until the next natural sunrise). */
  markSky(): void {
    this.levelAdmin().sky = true;
    this.lastDayTime = this.server.level.dayTime;
  }

  markEntity(e: Entity, on = true): void {
    if (on) e.admin = true;
  }

  // Block marks --------------------------------------------------------

  private dimMarks(dim: string): Map<number, Set<number>> {
    let m = this.blockMarks.get(dim);
    if (!m) {
      m = new Map();
      this.blockMarks.set(dim, m);
    }
    return m;
  }

  blockMarked(dim: Dimension, x: number, y: number, z: number): boolean {
    if (this.chunkMarks.get(dim.id)?.has(chunkIndex(x >> 4, z >> 4))) return true;
    const set = this.blockMarks.get(dim.id)?.get(chunkIndex(x >> 4, z >> 4));
    return !!set && set.has((y << 8) | ((z & 15) << 4) | (x & 15));
  }

  setBlockMark(dim: Dimension, x: number, y: number, z: number, on: boolean): void {
    if (y < 0 || y > 255) return;
    const k = chunkIndex(x >> 4, z >> 4);
    const m = this.dimMarks(dim.id);
    const idx = (y << 8) | ((z & 15) << 4) | (x & 15);
    if (on) {
      let set = m.get(k);
      if (!set) {
        set = new Set();
        m.set(k, set);
      }
      set.add(idx);
      // A chunk full of cheat blocks is simply marked as a whole
      if (set.size > 4096) {
        this.markChunk(dim, x >> 4, z >> 4);
        m.delete(k);
      }
    } else {
      const set = m.get(k);
      if (!set) return;
      set.delete(idx);
      if (!set.size) m.delete(k);
    }
  }

  markChunk(dim: Dimension, cx: number, cz: number): void {
    let s = this.chunkMarks.get(dim.id);
    if (!s) {
      s = new Set();
      this.chunkMarks.set(dim.id, s);
    }
    s.add(chunkIndex(cx, cz));
  }

  // XP -----------------------------------------------------------------

  /** Records experience that came from a cheat. */
  addAdminXp(p: ServerPlayer, amount: number): void {
    if (amount > 0) p.cheat.xp = Math.min(p.xpTotal, p.cheat.xp + amount);
  }

  /** Experience was spent or lost: the cheat share goes first. */
  onXpLost(p: ServerPlayer, lost: number): void {
    if (lost <= 0) return;
    p.cheat.xp = Math.max(0, Math.min(p.xpTotal, p.cheat.xp - lost));
  }

  /** Level reached with legitimately earned experience only. */
  legitLevel(p: ServerPlayer): number {
    let remaining = Math.max(0, p.xpTotal - p.cheat.xp);
    let level = 0;
    for (;;) {
      const need = level >= 30 ? 112 + (level - 30) * 9 : level >= 15 ? 37 + (level - 15) * 5 : 7 + level * 2;
      if (remaining < need) return level;
      remaining -= need;
      level++;
    }
  }

  // Travel ---------------------------------------------------------------

  /** A cheat moved the player: mark where they arrived. */
  onAdminArrival(p: ServerPlayer, dim: DimensionId, x: number, z: number, crossDim: boolean): void {
    const c = p.cheat;
    // Another dimension reached by a cheat: the whole visit is covered until the
    // player leaves it normally. Within a dimension (or back home to the
    // overworld): the arrival area is covered until the player walks out of it.
    if (crossDim && dim !== 'overworld') {
      c.visit = dim;
      return;
    }
    if (crossDim) c.visit = null;
    if (!c.zones.some((zn) => zn.dim === dim && (zn.x - x) ** 2 + (zn.z - z) ** 2 < 32 * 32)) {
      c.zones.push({ dim, x, z });
      if (c.zones.length > MAX_ADMIN_ZONES) c.zones.shift();
    }
  }

  /** Arrival areas end once the player has walked out of them. */
  private expireZones(): void {
    const r2 = (ADMIN_ZONE_RADIUS + 8) ** 2;
    for (const p of this.server.players.values()) {
      const c = p.cheat;
      if (!c.zones.length || !p.dim) continue;
      c.zones = c.zones.filter((z) => z.dim !== p.dim.id || (p.x - z.x) ** 2 + (p.z - z.z) ** 2 < r2);
    }
  }

  /** Normal travel (portals, respawning) ends a cheat visit. */
  onNormalDimensionChange(p: ServerPlayer): void {
    p.cheat.visit = null;
  }

  // ------------------------------------------------------------------ requests

  handle(p: ServerPlayer, req: number, raw: unknown): void {
    const reply = (ok: boolean, text: string, data?: unknown): void => p.send({ t: 'admin_result', req, ok, text, data });
    const action = validateAdmin(raw);
    if (!action) return reply(false, 'Invalid request.');
    if (action.a === 'set_cheats') {
      // Only the world's owner may switch cheats on or off
      if (this.server.roleOf(p) !== 'owner') return reply(false, 'Only the world owner can change the cheats setting.');
      this.setCheats(action.on, p);
      return reply(true, `Cheats ${action.on ? 'enabled' : 'disabled'} for this world.`);
    }
    if (!this.allowed(p)) {
      this.server.log(`[admin] denied ${action.a} from ${p.name}`);
      return reply(false, this.server.level.cheats ? 'You need operator permission to use the Admin Panel.' : 'Cheats are disabled in this world.');
    }
    // Simple flood control: a burst of 20, then 10 per second
    const b = (this.budget.get(p) ?? 0) + 1;
    if (b > 20) return reply(false, 'Too many admin requests. Slow down a little.');
    this.budget.set(p, b);
    try {
      const out = this.run(() => this.execute(p, req, action));
      if (out) reply(out.ok, out.text, out.data);
      if (action.a !== 'catalog' && action.a !== 'perf' && !action.a.startsWith('locate')) this.server.log(`[admin] ${p.name}: ${JSON.stringify(action)}`);
    } catch (e) {
      reply(false, `Failed: ${(e as Error).message}`);
    }
  }

  private target(p: ServerPlayer, name?: string): ServerPlayer | null {
    if (!name) return p;
    for (const o of this.server.players.values()) if (o.name.toLowerCase() === name.toLowerCase()) return o;
    return null;
  }

  private execute(p: ServerPlayer, req: number, a: AdminAction): { ok: boolean; text: string; data?: unknown } | null {
    const s = this.server;
    switch (a.a) {
      case 'catalog':
        return { ok: true, text: '', data: this.catalog() };
      case 'give': {
        const t = this.target(p, a.target);
        if (!t) return { ok: false, text: 'Player not found.' };
        return this.give(t, a.item, a.count, { potion: a.potion, enchant: a.enchant, level: a.level });
      }
      case 'spawn':
        return this.spawn(p, a.mob, a.count);
      case 'locate_structure':
      case 'tp_structure':
      case 'locate_biome':
      case 'tp_biome':
        return this.startSearch(p, req, a);
      case 'tp_player': {
        const t = this.target(p, a.target);
        if (!t || t === p) return { ok: false, text: 'Player not found.' };
        this.moveTo(p, t.dim.id, t.x, t.y, t.z);
        return { ok: true, text: `Teleported to ${t.name}.` };
      }
      case 'bring_player': {
        const t = this.target(p, a.target);
        if (!t || t === p) return { ok: false, text: 'Player not found.' };
        this.moveTo(t, p.dim.id, p.x, p.y, p.z);
        t.send({ t: 'chat', text: `${p.name} teleported you to them.`, kind: 'system' });
        return { ok: true, text: `Brought ${t.name} to you.` };
      }
      case 'gamemode': {
        const t = this.target(p, a.target);
        if (!t) return { ok: false, text: 'Player not found.' };
        this.setGamemode(t, a.mode);
        return { ok: true, text: `${t === p ? 'Your' : t.name + "'s"} game mode is now ${a.mode}.` };
      }
      case 'time':
        s.level.dayTime = a.value;
        this.markSky();
        s.sendTime();
        return { ok: true, text: `Time set to ${a.value}.` };
      case 'weather':
        s.interaction.weather.set(a.kind);
        this.markSky();
        s.sendTime();
        return { ok: true, text: `Weather set to ${a.kind}.` };
      case 'difficulty':
        if (s.level.hardcore) return { ok: false, text: 'Difficulty is locked in Hardcore worlds.' };
        s.level.difficulty = a.value;
        for (const o of s.players.values()) o.send({ t: 'world_info', world: s.worldInfo(o) });
        return { ok: true, text: `Difficulty set to ${a.value}.` };
      case 'pvp':
        s.level.pvp = a.on;
        for (const o of s.players.values()) o.send({ t: 'world_info', world: s.worldInfo(o) });
        s.broadcastChat(`PvP has been turned ${a.on ? 'on' : 'off'}`, 'announce');
        return { ok: true, text: `PvP ${a.on ? 'on' : 'off'}.` };
      case 'clear_mobs': {
        let n = 0;
        for (const e of [...p.dim.entitiesNear(p.x, p.y, p.z, a.radius)]) {
          if (!(e instanceof Mob) || e.removed || e.dead) continue;
          if (a.hostileOnly && e.def.category !== 'monster' && e.def.category !== 'boss') continue;
          // Pets and named mobs stay unless they are hostile
          if ((e.owner || e.customName) && e.def.category !== 'monster') continue;
          if (e.def.category === 'boss' && s.theEnd?.fight.dragon === e) continue;
          e.remove();
          n++;
        }
        return { ok: true, text: `Removed ${n} mob${n === 1 ? '' : 's'}.` };
      }
      case 'heal': {
        const t = this.target(p, a.target);
        if (!t) return { ok: false, text: 'Player not found.' };
        if (Number.isFinite(t.maxHealth)) t.health = t.maxHealth;
        t.food = 20;
        t.saturation = 20;
        t.air = t.maxAir;
        (t as { fireTicks?: number }).fireTicks = 0;
        t.statsDirty = true;
        return { ok: true, text: `Healed ${t.name}.` };
      }
      case 'health': {
        const t = this.target(p, a.target);
        if (!t) return { ok: false, text: 'Player not found.' };
        if (!Number.isFinite(t.maxHealth)) return { ok: false, text: `${t.name} has infinite health.` };
        t.health = Math.max(1, Math.min(t.maxHealth, a.value));
        t.statsDirty = true;
        return { ok: true, text: `${t.name}'s health is now ${t.health / 2} hearts.` };
      }
      case 'hunger': {
        const t = this.target(p, a.target);
        if (!t) return { ok: false, text: 'Player not found.' };
        t.food = a.value;
        t.saturation = Math.min(t.saturation, a.value);
        t.statsDirty = true;
        return { ok: true, text: `${t.name}'s hunger is now ${a.value}/20.` };
      }
      case 'xp': {
        const t = this.target(p, a.target);
        if (!t) return { ok: false, text: 'Player not found.' };
        const cur = t.xpLevel().level;
        const level = Math.max(0, a.mode === 'set' ? a.levels : cur + a.levels);
        this.setXpLevel(t, level);
        return { ok: true, text: `${t.name} is now level ${level}.` };
      }
      case 'clear_inventory': {
        const t = this.target(p, a.target);
        if (!t) return { ok: false, text: 'Player not found.' };
        t.inventory.clear();
        t.cursor = null;
        s.interaction.syncInventory(t);
        s.interaction.survival.updateArmor(t);
        return { ok: true, text: `Cleared ${t.name}'s inventory.` };
      }
      case 'flight': {
        const t = this.target(p, a.target);
        if (!t) return { ok: false, text: 'Player not found.' };
        if (t.gamemode === 'spectator' || t.gamemode === 'creative') return { ok: false, text: `${t.name} can already fly in ${t.gamemode} mode.` };
        t.abilities.mayFly = a.on;
        if (!a.on) t.abilities.flying = false;
        t.cheat.flight = a.on;
        t.send({ t: 'abilities', abilities: t.abilitiesMsg() });
        return { ok: true, text: `Flight ${a.on ? 'enabled' : 'disabled'} for ${t.name}.` };
      }
      case 'regen_chunk': {
        const cx = Math.floor(p.x) >> 4;
        const cz = Math.floor(p.z) >> 4;
        const fresh = p.dim.generator.generate(cx, cz);
        let n = 0;
        for (let y = 0; y < 256; y++)
          for (let z = 0; z < 16; z++)
            for (let x = 0; x < 16; x++) {
              const st = fresh.get(x, y, z);
              const wx = (cx << 4) + x;
              const wz = (cz << 4) + z;
              if (p.dim.getState(wx, y, wz) !== st) {
                p.dim.setBlock(wx, y, wz, st, { updateNeighbors: false });
                n++;
              }
            }
        this.markChunk(p.dim, cx, cz);
        return { ok: true, text: `Regenerated chunk ${cx}, ${cz} (${n} blocks changed).` };
      }
      case 'reload_chunks':
        for (const k of [...p.sentChunks]) p.sentChunks.delete(k);
        p.chunkX = NaN;
        return { ok: true, text: 'Resending nearby chunks.' };
      case 'perf':
        return { ok: true, text: '', data: this.perf() };
      case 'endgame':
        return this.endgame(p, a.op, a.id);
      case 'v4':
        return this.v4(p, a.op);
      default:
        return { ok: false, text: 'Unknown action.' };
    }
  }

  /** V4: the Glitched Structure's quest, bunkers, and a fluid test rig. Everything here is a cheat. */
  private v4(p: ServerPlayer, op: V4Op): { ok: boolean; text: string; data?: unknown } {
    const s = this.server;
    if (s.level.generatorVersion < 4) return { ok: false, text: 'This world was created before the World Update (V4).' };
    const gq = s.glitchedQuest;
    const e = gq?.errorAt(p) ?? null;
    const key = e ? GlitchedQuestSystem.key(p.dim, e) : null;
    const status = (): Record<string, unknown> => {
      const rec = key ? s.level.quests.glitch[key] : undefined;
      const f = key ? gq?.fights.get(key) : undefined;
      const bunker = this.bunkerHere(p);
      const brec = bunker ? s.level.quests.bunker[StructureQuests.key(bunker)] : undefined;
      return {
        inErrorBiome: !!e,
        glitch: e ? { stage: rec?.stage ?? 0, done: rec?.done ?? false, fighting: f ? f.stage : null, mobs: f?.mobs.length ?? 0 } : null,
        bunker: bunker ? { stage: brec?.stage ?? 0, done: brec?.done ?? false } : null,
      };
    };
    switch (op) {
      case 'status':
        return { ok: true, text: '', data: status() };
      case 'glitch_start': {
        if (!e || !gq || !key) return { ok: false, text: 'Stand in an Error Biome chunk first (Teleport: Glitched Structure).' };
        const rec = gq.record(key);
        if (rec.done) return { ok: false, text: 'This Glitched Structure is complete. Reset it first.' };
        if (gq.fights.has(key)) return { ok: false, text: 'A stage is already in progress.' };
        const f = gq.start(p.dim, e, rec.stage + 1, true);
        return f ? { ok: true, text: `Stage ${f.stage} started (as a cheat).`, data: status() } : { ok: false, text: 'Could not start the stage.' };
      }
      case 'glitch_clear':
        if (!key || !gq?.adminClear(key)) return { ok: false, text: 'No stage is in progress here.' };
        return { ok: true, text: 'Stage cleared (as a cheat).', data: status() };
      case 'glitch_reset':
        if (!e || !gq) return { ok: false, text: 'Stand in an Error Biome chunk first.' };
        gq.adminReset(p.dim, e);
        return { ok: true, text: 'The Glitched Structure was reset: every firewall is shut again.', data: status() };
      case 'glitch_reward': {
        const loot = rollLoot('quest/glitched_reward', { rng: new Random() });
        for (const st of loot) {
          const rest = p.inventory.add(markAdmin(st));
          if (rest) s.interaction.dropStack(p, rest);
        }
        s.interaction.syncInventory(p);
        return { ok: true, text: `Gave a Glitched Structure reward roll: ${loot.map((st: ItemStack) => itemOf(st.id)?.def.name).join(', ')}.` };
      }
      case 'bunker_reset': {
        const b = this.bunkerHere(p);
        if (!b || b.quest?.kind !== 'bunker') return { ok: false, text: 'Stand inside a bunker first.' };
        const q = b.quest;
        delete s.level.quests.bunker[StructureQuests.key(b)];
        const dim = p.dim;
        const lit = (pos: [number, number, number], on: boolean): void => {
          const st = dim.getState(...pos);
          if (hasProp(st, 'lit')) dim.setBlock(...pos, withProp(st, 'lit', on ? 'true' : 'false'));
        };
        lit(q.reader, false);
        for (const g of q.generators) lit(g, false);
        for (const d of q.doors) {
          const st = dim.getState(...d);
          if (hasProp(st, 'open')) dim.setBlock(...d, withProp(st, 'open', 'false'), { updateNeighbors: false });
        }
        for (const b2 of q.blast) dim.setBlock(...b2, S('bunker_blast_door'));
        return { ok: true, text: 'The bunker was reset.', data: status() };
      }
      case 'fluid_rig': {
        // A glass tank beside the player: a water channel running into lava sources and flowing lava
        const dim = p.dim;
        const x0 = Math.floor(p.x) + 3;
        const y0 = Math.floor(p.y);
        const z0 = Math.floor(p.z) - 4;
        for (let x = 0; x < 9; x++)
          for (let z = 0; z < 9; z++)
            for (let y = -1; y <= 3; y++) {
              const wall = x === 0 || x === 8 || z === 0 || z === 8 || y === -1;
              dim.setBlock(x0 + x, y0 + y, z0 + z, wall ? S('glass') : 0);
              this.setBlockMark(dim, x0 + x, y0 + y, z0 + z, true);
            }
        const mark = (x: number, y: number, z: number, st: number): void => {
          dim.setBlock(x0 + x, y0 + y, z0 + z, st);
          this.setBlockMark(dim, x0 + x, y0 + y, z0 + z, true);
        };
        for (let x = 1; x < 8; x++) mark(x, 0, 4, S('stone'));
        mark(2, 0, 2, S('lava'));
        // Lava falling from a source keeps a stream of flowing lava for the water to meet
        mark(6, 2, 2, S('lava'));
        mark(4, 0, 6, S('lava'));
        mark(4, 2, 4, S('water'));
        mark(2, 2, 6, S('water'));
        return { ok: true, text: 'Fluid test rig built: watch water meet lava sources (obsidian) and flowing lava (cobblestone).' };
      }
    }
    return { ok: false, text: 'Unknown operation.' };
  }

  /** The bunker whose area the player stands in, if any. */
  private bunkerHere(p: ServerPlayer): Start | null {
    const g = p.dim.generator as { questStartsAt?(cx: number, cz: number): Start[] };
    const list = g.questStartsAt?.(Math.floor(p.x) >> 4, Math.floor(p.z) >> 4) ?? [];
    return (
      list.find((b) => {
        if (b.quest?.kind !== 'bunker') return false;
        const a = b.quest.area;
        return p.x >= a.x0 && p.x <= a.x1 + 1 && p.z >= a.z0 && p.z <= a.z1 + 1 && p.y >= a.y0 - 1 && p.y <= a.y1 + 2;
      }) ?? null
    );
  }

  /** V3: endings and The Error. Forced endings are remembered as forced, never as reached. */
  private endgame(p: ServerPlayer, op: 'status' | 'reset_endings' | 'force_ending' | 'reset_error', id?: string): { ok: boolean; text: string; data?: unknown } {
    const s = this.server;
    const e = s.endings;
    if (!e) return { ok: false, text: 'Endings are not available.' };
    switch (op) {
      case 'reset_endings':
        e.reset();
        delete s.level.flags.errorCalm;
        return { ok: true, text: 'Every ending in this world was reset.', data: this.endgameStatus() };
      case 'force_ending':
        if (!e.force(p, id!)) return { ok: false, text: 'Unknown ending.' };
        return { ok: true, text: 'Ending forced (as a cheat).', data: this.endgameStatus() };
      case 'reset_error': {
        const f = s.errorBoss?.fight;
        if (f) s.errorBoss!.reset(f);
        e.state.errorDefeated = false;
        delete s.level.flags.errorCalm;
        return { ok: true, text: f ? 'The Error was reset; its arena is restored.' : 'The Error can form again.', data: this.endgameStatus() };
      }
      default:
        return { ok: true, text: '', data: this.endgameStatus() };
    }
  }

  private endgameStatus(): Record<string, unknown> {
    const s = this.server;
    const st = s.endings!.state;
    return { dragonDeath: st.dragonDeath, reached: Object.keys(st.reached), forced: st.forced, eyeAwarded: st.eyeAwarded, farlandsAccess: st.farlandsAccess, errorDefeated: st.errorDefeated, error: s.errorBoss?.status() ?? null };
  }

  private setCheats(on: boolean, by: ServerPlayer): void {
    const s = this.server;
    s.level.cheats = on;
    for (const o of s.players.values()) o.send({ t: 'world_info', world: s.worldInfo(o) });
    s.broadcastChat(`${by.name} ${on ? 'enabled' : 'disabled'} cheats for this world`, 'announce');
  }

  // ------------------------------------------------------------------ give / spawn

  give(t: ServerPlayer, id: string, count: number, opts: { potion?: string; enchant?: string; level?: number } = {}): { ok: boolean; text: string } {
    const it = itemById.get(id);
    if (!it || it.num === 0 || id === 'air') return { ok: false, text: `Unknown item ${id}.` };
    const proto: ItemStack = { id: it.num, count: 1 };
    if (opts.potion) {
      if (!POTION_BY_ID.has(opts.potion) || (it.id !== 'potion' && it.id !== 'splash_potion')) return { ok: false, text: 'That potion type does not exist.' };
      proto.tag = { potion: opts.potion };
    }
    if (opts.enchant) {
      if (!ENCHANT_BY_ID.has(opts.enchant)) return { ok: false, text: 'Unknown enchantment.' };
      const lvl = Math.max(1, Math.min(10, opts.level ?? 1));
      proto.tag = { ...(proto.tag ?? {}), ...(it.id === 'enchanted_book' ? { stored: { [opts.enchant]: lvl } } : { ench: { [opts.enchant]: lvl } }) };
    }
    markAdmin(proto);
    // Unstackable items: at most a full inventory; the rest would only litter the ground
    const max = it.maxStack === 1 ? 36 : 64 * 36;
    const total = Math.min(count, max);
    let left = total;
    let dropped = 0;
    while (left > 0) {
      const n = Math.min(left, it.maxStack);
      const st: ItemStack = { ...proto, count: n, ...(proto.tag ? { tag: JSON.parse(JSON.stringify(proto.tag)) } : {}) };
      const rem = t.inventory.add(st);
      if (rem) {
        if (dropped < 64) this.server.interaction.dropStack(t, rem);
        dropped++;
      }
      left -= n;
    }
    this.server.interaction.syncInventory(t);
    const nm = it.def.name + (opts.potion ? ` (${POTION_BY_ID.get(opts.potion)!.name})` : '') + (opts.enchant ? ` (${ENCHANT_BY_ID.get(opts.enchant)!.name} ${opts.level ?? 1})` : '');
    return { ok: true, text: `Gave ${total} ${nm} to ${t.name}${total < count ? ` (limited to ${total})` : ''}${dropped ? '; some were dropped at their feet' : ''}.` };
  }

  spawn(p: ServerPlayer, type: string, count: number): { ok: boolean; text: string } {
    const s = this.server;
    const def = mobDef(type);
    if (!def || !s.mobs) return { ok: false, text: `Unknown mob ${type}.` };
    if (type === 'ender_dragon') {
      // In the End the dragon joins the real fight (with its arena rules)
      if (p.dim.id === 'end' && s.theEnd) {
        if (s.theEnd.fight.dragon) return { ok: false, text: 'An Ender Dragon is already alive here.' };
        const m = s.theEnd.fight.spawnDragon();
        if (!m) return { ok: false, text: 'Could not spawn the dragon.' };
        m.admin = true;
        return { ok: true, text: 'Spawned an Ender Dragon (admin: its defeat will not count for advancements).' };
      }
      count = 1;
    }
    const dir = [-Math.sin(p.yaw), -Math.cos(p.yaw)];
    let n = 0;
    if (type === 'warden' && s.warden) {
      // Wardens climb out of the ground like a summoned one, marked as admin
      // (never counts for advancements); capped so the panel can't flood a world
      count = Math.min(count, 3);
      for (let i = 0; i < count; i++) {
        const w = s.warden.summon(p.dim, p.x + dir[0]! * 6, p.y, p.z + dir[1]! * 6, null, { admin: true });
        if (w) n++;
      }
      return { ok: n > 0, text: n > 0 ? `Summoned ${n} admin Warden${n === 1 ? '' : 's'} (it will not count for advancements).` : 'No room for a Warden to emerge here.' };
    }
    for (let i = 0; i < count; i++) {
      const d = 3 + Math.min(4, def.width) + Math.random() * 2;
      const x = p.x + dir[0]! * d + (Math.random() - 0.5) * 3;
      const z = p.z + dir[1]! * d + (Math.random() - 0.5) * 3;
      const y = this.standY(p.dim, x, p.y, z) ?? p.y;
      const m = s.mobs.spawn(p.dim, type, x, y, z, { reason: 'admin', persistent: true });
      if (!m) continue;
      m.admin = true;
      n++;
    }
    return { ok: n > 0, text: n > 0 ? `Spawned ${n} ${def.name}${n === 1 ? '' : 's'}.` : `Could not spawn ${def.name}.` };
  }

  /** A standing height near y at a column (loaded chunks only). */
  private standY(dim: Dimension, x: number, y: number, z: number): number | null {
    const bx = Math.floor(x);
    const bz = Math.floor(z);
    if (!dim.isLoaded(bx, bz)) return null;
    for (let dy = 0; dy < 12; dy++) {
      for (const yy of [Math.floor(y) + dy, Math.floor(y) - dy]) {
        if (yy < 1 || yy > 254) continue;
        if (STATE_SOLID[dim.getState(bx, yy - 1, bz)] && !STATE_SOLID[dim.getState(bx, yy, bz)] && !STATE_SOLID[dim.getState(bx, yy + 1, bz)]) return yy;
      }
    }
    return null;
  }

  setGamemode(t: ServerPlayer, mode: (typeof t)['gamemode']): void {
    const s = this.server;
    t.setGamemode(mode);
    t.maxHealth = maxHealthFor(mode, s.level.godHearts);
    if (Number.isFinite(t.maxHealth)) t.health = Math.min(Math.max(t.health, 1), t.maxHealth);
    else t.health = 20;
    // The world's own mode is normal play; anything else was set by a cheat
    const worldMode = s.level.mode;
    t.cheat.mode = mode !== worldMode;
    t.cheat.flight = false;
    t.statsDirty = true;
    t.send({ t: 'gamemode', mode, abilities: t.abilitiesMsg() });
    s.sendPlayerList();
  }

  setXpLevel(t: ServerPlayer, level: number): void {
    const legit = Math.max(0, t.xpTotal - t.cheat.xp);
    const total = xpForLevel(level);
    t.xpTotal = total;
    // Anything above what the player earned is cheat experience
    t.cheat.xp = Math.max(0, total - legit);
    t.statsDirty = true;
  }

  // ------------------------------------------------------------------ teleport

  /** Moves a player as a cheat (marks the arrival for advancement safety). */
  moveTo(t: ServerPlayer, dim: DimensionId, x: number, y: number, z: number): void {
    const s = this.server;
    const cross = t.dim.id !== dim;
    this.onAdminArrival(t, dim, x, z, cross);
    if (cross) s.changeDimension(t, dim, x, y, z, t.yaw, { admin: true });
    else s.teleport(t, x, y, z);
    t.spawnProtection = Math.max(t.spawnProtection, 60);
  }

  private startSearch(p: ServerPlayer, req: number, a: AdminAction & { a: 'locate_structure' | 'tp_structure' | 'locate_biome' | 'tp_biome' }): { ok: boolean; text: string } | null {
    const dim = this.server.dim(a.dim);
    if (this.searches.some((q) => q.p === p)) return { ok: false, text: 'A search is already running.' };
    // Search from the player's position, scaled into the target dimension
    const scale = p.dim.rules.scale / dim.rules.scale;
    const ox = p.dim === dim ? p.x : p.x * scale;
    const oz = p.dim === dim ? p.z : p.z * scale;
    let steps: Search['steps'];
    let id: string;
    if (a.a === 'locate_structure' || a.a === 'tp_structure') {
      id = a.structure;
      const g = dim.generator;
      if (!g.structureTypes?.().includes(id) || !g.locateSteps) return { ok: false, text: `${structureName(id)} does not generate in the ${a.dim}.` };
      steps = g.locateSteps(id, Math.floor(ox), Math.floor(oz));
    } else if (a.biome.startsWith('cave:')) {
      // V2 underground: cave biomes, mega-caverns and ravines
      id = a.biome.slice(5);
      if (!dim.generator.caveSteps || !dim.generator.caves || !caveFeatures().some((f) => f.id === id)) return { ok: false, text: `${caveFeatureName(id)} does not generate in the ${a.dim}${a.dim === 'overworld' ? ' of this world (created before the Caves Update)' : ''}.` };
      steps = dim.generator.caveSteps(id, Math.floor(ox), Math.floor(oz));
      this.searches.push({ p, req, kind: 'cave', dim: a.dim, id, teleport: a.a.startsWith('tp_'), steps, started: this.server.tickNo });
      return null;
    } else {
      id = a.biome;
      const b = biomes.find((bb) => bb.id === id);
      if (!b || b.dimension !== a.dim) return { ok: false, text: `That biome does not exist in the ${a.dim}.` };
      steps = biomeSteps(dim, b.num, Math.floor(ox), Math.floor(oz));
    }
    this.searches.push({ p, req, kind: a.a.includes('structure') ? 'structure' : 'biome', dim: a.dim, id, teleport: a.a.startsWith('tp_'), steps, started: this.server.tickNo });
    return null; // replied when the search finishes
  }

  // ------------------------------------------------------------------ tick

  tick(): void {
    for (const [p, b] of this.budget) {
      if (b <= 0.5 || !this.server.players.has(p.conn.id)) this.budget.delete(p);
      else this.budget.set(p, b - 0.5);
    }
    this.runSearches();
    this.runPending();
    if (this.server.tickNo % 20 === 0) this.expireZones();
    // A cheat-set time or weather lasts until the next natural sunrise
    const l = this.server.level;
    const la = this.levelAdmin();
    if (la.sky && this.lastDayTime >= 0 && l.dayTime < this.lastDayTime && l.dayTime < 2000 && !l.raining) la.sky = false;
    this.lastDayTime = l.dayTime;
  }

  private runSearches(): void {
    const t0 = performance.now();
    while (this.searches.length && performance.now() - t0 < SEARCH_BUDGET_MS) {
      const q = this.searches[0]!;
      if (!this.server.players.has(q.p.conn.id)) {
        this.searches.shift();
        continue;
      }
      let done: IteratorResult<void, { x: number; y: number; z: number } | null> | null = null;
      while (performance.now() - t0 < SEARCH_BUDGET_MS) {
        done = q.steps.next();
        if (done.done) break;
      }
      if (!done?.done) break; // out of budget; continue next tick
      this.searches.shift();
      this.finishSearch(q, done.value);
    }
  }

  private finishSearch(q: Search, pos: { x: number; y: number; z: number } | null): void {
    const p = q.p;
    const label = q.kind === 'structure' ? structureName(q.id) : q.kind === 'cave' ? caveFeatureName(q.id) : biomes.find((b) => b.id === q.id)?.name ?? q.id;
    if (!pos) {
      p.send({ t: 'admin_result', req: q.req, ok: false, text: `No ${label} found within range in the ${q.dim}.` });
      return;
    }
    const dim = this.server.dim(q.dim);
    const scale = p.dim.rules.scale / dim.rules.scale;
    const sx = p.dim === dim ? p.x : p.x * scale;
    const sz = p.dim === dim ? p.z : p.z * scale;
    const res: LocateResult = { kind: q.kind, id: q.id, name: label, dim: q.dim, x: pos.x, y: pos.y, z: pos.z, distance: Math.round(Math.hypot(pos.x - sx, pos.z - sz)) };
    if (!q.teleport) {
      p.send({ t: 'admin_result', req: q.req, ok: true, text: `Nearest ${label}: ${res.distance} blocks away in the ${q.dim}.`, data: res });
      return;
    }
    this.pending.push({ p, req: q.req, dim: q.dim, x: pos.x, y: pos.y, z: pos.z, label, surface: q.kind === 'biome', since: this.server.tickNo });
    p.send({ t: 'admin_result', req: q.req, ok: true, text: `Found ${label} ${res.distance} blocks away. Preparing a safe landing...`, data: { ...res, pending: true } });
  }

  /** Waits for the destination to generate, then lands the player somewhere safe. */
  private runPending(): void {
    for (let i = this.pending.length - 1; i >= 0; i--) {
      const t = this.pending[i]!;
      const s = this.server;
      if (!s.players.has(t.p.conn.id)) {
        this.pending.splice(i, 1);
        continue;
      }
      const dim = s.dim(t.dim);
      const cx = Math.floor(t.x) >> 4;
      const cz = Math.floor(t.z) >> 4;
      dim.want(cx, cz, 1, s.tickNo);
      let loaded = true;
      for (let dx = -1; dx <= 1 && loaded; dx++) for (let dz = -1; dz <= 1 && loaded; dz++) if (!dim.isLoaded((cx + dx) << 4, (cz + dz) << 4)) loaded = false;
      if (!loaded) {
        if (s.tickNo - t.since > 20 * 60) {
          this.pending.splice(i, 1);
          t.p.send({ t: 'admin_result', req: t.req, ok: false, text: `Timed out waiting for the ${t.label} area to generate.` });
        }
        continue;
      }
      this.pending.splice(i, 1);
      const spot = this.safeSpot(dim, t.x, t.y, t.z, t.surface);
      if (!spot) {
        t.p.send({ t: 'admin_result', req: t.req, ok: false, text: `No safe landing spot near the ${t.label}.` });
        continue;
      }
      this.run(() => this.moveTo(t.p, t.dim, spot.x + 0.5, spot.y, spot.z + 0.5));
      t.p.send({ t: 'admin_result', req: t.req, ok: true, text: `Teleported to the ${t.label} at ${spot.x}, ${spot.y}, ${spot.z}.`, data: { teleported: true } });
    }
  }

  /**
   * A standing spot near a target: two blocks of air (no fluids or fire) over
   * a solid, harmless floor, with no lava next to it. Searches outwards from
   * the target (structure start or biome sample), preferring its own height.
   */
  safeSpot(dim: Dimension, x: number, y: number, z: number, surface: boolean): { x: number; y: number; z: number } | null {
    const bx = Math.floor(x);
    const bz = Math.floor(z);
    const ok = (px: number, py: number, pz: number): boolean => {
      if (py < 1 || py > 253) return false;
      const floor = dim.getState(px, py - 1, pz);
      const a = dim.getState(px, py, pz);
      const b = dim.getState(px, py + 1, pz);
      if (!STATE_SOLID[floor] || STATE_FLUID[floor]) return false;
      if (STATE_SOLID[a] || STATE_SOLID[b] || STATE_FLUID[a] || STATE_FLUID[b]) return false;
      for (const st of [floor, a, b]) if (HAZARD.test(blocks[STATE_BLOCK[st]!]!.id)) return false;
      // No lava or fire right next to the feet or head
      for (const [dx, dz] of [
        [1, 0],
        [-1, 0],
        [0, 1],
        [0, -1],
      ] as const) {
        for (const yy of [py - 1, py, py + 1]) {
          const n = dim.getState(px + dx, yy, pz + dz);
          if (STATE_FLUID[n] === 2 || /fire|lava|magma/.test(blocks[STATE_BLOCK[n]!]!.id)) return false;
        }
      }
      return true;
    };
    const tryColumn = (px: number, pz: number, aroundY: number, range: number): number | null => {
      for (let dy = 0; dy <= range; dy++) {
        for (const yy of dy === 0 ? [aroundY] : [aroundY + dy, aroundY - dy]) if (ok(px, yy, pz)) return yy;
      }
      return null;
    };
    if (!surface) {
      // Near the structure itself (underground rooms, floating cities...)
      for (let r = 0; r <= 10; r++) {
        for (let dx = -r; dx <= r; dx++)
          for (let dz = -r; dz <= r; dz++) {
            if (Math.max(Math.abs(dx), Math.abs(dz)) !== r) continue;
            const yy = tryColumn(bx + dx, bz + dz, Math.floor(y), 12);
            if (yy !== null) return { x: bx + dx, y: yy, z: bz + dz };
          }
      }
    }
    // The surface around the target column
    for (let r = 0; r <= 24; r++) {
      for (let dx = -r; dx <= r; dx++)
        for (let dz = -r; dz <= r; dz++) {
          if (Math.max(Math.abs(dx), Math.abs(dz)) !== r) continue;
          const top = this.server.findSafeY(dim, bx + dx, bz + dz);
          if (top === null) continue;
          if (ok(bx + dx, top, bz + dz)) return { x: bx + dx, y: top, z: bz + dz };
        }
    }
    return null;
  }

  // ------------------------------------------------------------------ info

  catalog(): AdminCatalog {
    const s = this.server;
    const structures: Record<string, string[]> = {};
    const bl: AdminCatalog['biomes'] = {};
    const caves: NonNullable<AdminCatalog['caves']> = {};
    for (const d of ADMIN_DIMENSIONS) {
      structures[d] = s.dim(d).generator.structureTypes?.() ?? [];
      if (s.dim(d).generator.caves) caves[d] = caveFeatures();
      bl[d] = biomes.filter((b) => b.dimension === d && b.id !== 'error_biome').map((b) => ({ id: b.id, name: b.name }));
    }
    return {
      structures,
      biomes: bl,
      mobs: MOB_DEFS.map((m) => ({ id: m.id, name: m.name, category: m.category })),
      players: [...s.players.values()].map((o) => o.name),
      caves,
    };
  }

  perf(): Record<string, string | number> {
    const s = this.server;
    let chunks = 0;
    let ents = 0;
    let mobs = 0;
    for (const d of s.dims.values()) {
      chunks += d.chunks.size;
      ents += d.entities.size;
      for (const e of d.entities.values()) if (e instanceof Mob) mobs++;
    }
    const ow = s.overworld;
    const mem = (globalThis as { process?: { memoryUsage?: () => { heapUsed: number } } }).process?.memoryUsage?.().heapUsed ?? (performance as unknown as { memory?: { usedJSHeapSize: number } }).memory?.usedJSHeapSize ?? 0;
    return {
      tps: +Math.min(20, 1000 / Math.max(50, s.avgTickMs)).toFixed(1),
      tickMs: +s.avgTickMs.toFixed(2),
      chunks,
      entities: ents,
      mobs,
      players: s.players.size,
      genMsPerChunk: ow.genCount ? +(ow.genMsTotal / ow.genCount).toFixed(2) : 0,
      pendingGeneration: ow.pendingGeneration,
      serverHeapMB: mem ? Math.round(mem / 1048576) : 0,
    };
  }

  // ------------------------------------------------------------------ persistence

  private levelAdmin(): LevelAdmin {
    const l = this.server.level as unknown as { admin?: LevelAdmin };
    if (!l.admin) l.admin = {};
    return l.admin;
  }

  private load(): void {
    const la = this.levelAdmin();
    for (const [dim, map] of Object.entries(la.blocks ?? {})) {
      const m = this.dimMarks(dim);
      for (const [k, list] of Object.entries(map)) if (Array.isArray(list)) m.set(Number(k), new Set(list.filter((n) => Number.isInteger(n))));
    }
    for (const [dim, list] of Object.entries(la.chunks ?? {})) if (Array.isArray(list)) this.chunkMarks.set(dim, new Set(list.filter((n) => Number.isFinite(n))));
  }

  /** Writes the block/chunk marks into the level data (called before saving). */
  persist(): void {
    const la = this.levelAdmin();
    la.blocks = {};
    for (const [dim, m] of this.blockMarks) {
      const out: Record<string, number[]> = {};
      for (const [k, set] of m) if (set.size) out[String(k)] = [...set];
      la.blocks[dim] = out;
    }
    la.chunks = {};
    for (const [dim, set] of this.chunkMarks) la.chunks[dim] = [...set];
  }
}

/** Nearest column of a biome, sampling rings outwards (coarser far away). */
function* biomeSteps(dim: Dimension, biome: number, x: number, z: number): Generator<void, { x: number; y: number; z: number } | null> {
  const g = dim.generator;
  if (g.biomeAt(x, z) === biome && (!g.landAt || g.landAt(x, z))) return { x, y: 64, z };
  let r = 16;
  while (r <= BIOME_RADIUS) {
    const step = r < 1024 ? 16 : r < 2048 ? 32 : 64;
    // Walk the square ring at distance r
    let best: { x: number; z: number; d: number } | null = null;
    for (let i = -r; i <= r; i += step) {
      for (const [px, pz] of [
        [x + i, z - r],
        [x + i, z + r],
        [x - r, z + i],
        [x + r, z + i],
      ] as const) {
        if (g.biomeAt(px, pz) !== biome || (g.landAt && !g.landAt(px, pz))) continue;
        const d = (px - x) ** 2 + (pz - z) ** 2;
        if (!best || d < best.d) best = { x: px, z: pz, d };
      }
    }
    if (best) {
      // Step a little further into the biome so the landing is inside it
      const dx = best.x - x;
      const dz = best.z - z;
      const len = Math.hypot(dx, dz) || 1;
      for (const push of [12, 6, 0]) {
        const px = Math.round(best.x + (dx / len) * push);
        const pz = Math.round(best.z + (dz / len) * push);
        if (g.biomeAt(px, pz) === biome && (!g.landAt || g.landAt(px, pz))) return { x: px, y: 64, z: pz };
      }
      return { x: best.x, y: 64, z: best.z };
    }
    r += step;
    yield;
  }
  return null;
}

void items;
void biomeOf;
void stackOf;

/** Cave features the admin cave finder knows (V2 overworld). */
function caveFeatures(): { id: string; name: string }[] {
  return [...CAVE_BIOMES.slice(1).map((b) => ({ id: b.id, name: b.name })), { id: 'mega_cavern', name: 'Mega-Cavern' }, { id: 'ravine', name: 'Ravine' }];
}

function caveFeatureName(id: string): string {
  return caveFeatures().find((f) => f.id === id)?.name ?? id;
}
